### ISSUE TITLE
Population Based Training [ChainerMN Feature request]

### ISSUE THREAD

**Issue by MannyKayy** [pfnet/optuna#287]
A very useful addition to the [pruning feature](https://github.com/pfnet/optuna/pull/286) with chainermn, would be the ability to automatically use [Population Based Training](https://arxiv.org/abs/1711.09846). It greatly reduces the hyper-parameter search cost (in terms of time and compute) in certain cases. 

Basically every _n_ trials, prune/overwrite the models for the _m_ worst preforming trials (model parameters and hyper-parameters) with those of the _o_ best trials, sample new hyper-parameters according to some scheme (e.g. TPE) and continue the optimization process from that point forward (instead of re-initializing the model at the start of every trial). This is pretty straight forward in the single-node multi-gpu setting but is abit more cumbersome in the multi-node multi-gpu setting.

**Comment by toshihikoyanase** [comment]
Thank you for your feature request. We also think PBT is a quite efficient method especially for optimization of neural network architectures.

I think we can implement PBT on Optuna, but it will take a substantial amount of implementation/deployment costs. This is because current Optuna does not have any mechanisms to share snapshots of models (e.g., weights of neural networks) among trials, which are required to implement 'exploit' step of PBT. The developers of PBT will need to implement the storage for model snapshots which works in parallel and distributed environments, and the users will need to deploy it by themselves.

For a meantime, we do not have plans to implement features to share model snapshots. If we receive such requests from many users, we'll prioritize the implementation of the snapshot feature and PBT.

By the way, [the successive halving algorithm](https://github.com/pfnet/optuna/pull/236) and [hyperband](https://github.com/pfnet/optuna/tree/hyperband), which are competitive methods with PBT, will be merged to master soon. We'll recommend them if you want to accelerate optimization.

**Comment by MannyKayy** [comment]
@toshihikoyanase Thanks for the pointer to the [ASHA pruner](https://github.com/pfnet/optuna/blob/master/optuna/pruners/successive_halving.py) (now merged). According to the [ICLR 2019 ASHA](https://openreview.net/forum?id=S1MAriC5F7) submission, ASHA > PBT in most cases so I will close out this issue.
