### ISSUE TITLE
add a scikit-learn compatible SearchCV class

### ISSUE THREAD

**Issue by Y-oHr-N** [pfnet/optuna#307]
Hi,

First of all, thanks for developing a nice package!

I am a heavy user of scikit-learn and often use `RandomizedSearchCV`.
So I have implemented a similar SearchCV class with Optuna.
https://github.com/Y-oHr-N/mllib/blob/master/mllib/model_selection.py

If you agree, I would like to contribute to Optuna by merging this code into your package.

Thanks.

**Comment by g-votte** [comment]
Thanks for your sharing the SearchCV implementation!

We think the interface is very powerful and makes Optuna much more user-friendly to sklearn users.

Especially because it’s powerful, Optuna dev team is internally discussing interface compatibility and other possible effects of introducing the sklearn interface. E.g., how/whether we can coordinate it with pruning and define-by-run.

We appreciate your patience for a while.

**Comment by Y-oHr-N** [comment]
I have read this article (written in Japanese).
https://medium.com/@tomoto/optuna%E3%81%AEpruning%E3%81%8C%E6%8A%B1%E3%81%88%E3%82%8B%E8%AA%B2%E9%A1%8C-1a1c9dd870df

Do you have any progress on pruning with cross-validation?

**Comment by g-votte** [comment]
Regarding @Y-oHr-N 's question about pruning with CV, Optuna can deal with this. Please find below a rough example of implementation using `partial_fit` interface.

We're facing a matter of design choice rather than a technical problem. We have several options to implement CV pruning other than the example below, and need to decide the best (default) behaviour. For example:

- **Option 1:** calculate intermediate CV score after each `partial_fit` (example below).
- **Option 2:** use each fold's score as an intermediate value.
- **Option 3:** without `partial_fit`, start training with a small potion of data; gradually increase the amount of data; and calculate intermediate CV score after each increase.

## CV Pruning Example with `partial_fit`
Modify the `Objective` class in: https://github.com/Y-oHr-N/mllib/blob/master/mllib/model_selection.py

```python
class Objective:
    ...

    def _call_with_pruning(self, trial):

        params = {
            name: trial._suggest(
                name, distribution
            ) for name, distribution in self.param_distributions.items()
        }

        trains, tests, estimators = [], [], []
        for train, test in self.cv.split(X, y, self.groups):
            trains.append(train)
            tests.append(test)

            estimator = clone(self.estimator)
            estimator.set_params(**params)
            estimators.append(estimator)

        classes = ...  # get a list of class
        last_score = None
        for step in range(self.n_partial_fit_loops):
            intermediate_values = []
            for i in range(self.cv.get_n_splits()):
                estimator = estimators[i]
                estimator.partial_fit(X[trains[i]], y[trains[i]], classes)
                score = ...  # run validation and get validation score
                intermediate_values.append(score)

            last_score = np.average(intermediate_values)
            trial.report(last_score, step)
            if trial.should_prune(step):
                raise TrialPruned()

        return last_score

    def __call__(self, trial):

        if self.pruning:
            return self._call_with_pruning(trial)
        else:
            return self._call_without_pruning(trial)  # invoke original __call__ logic

**Comment by g-votte** [comment]
Internal discussion in Optuna dev team:

- Pruning implementation
    - We prefer [Option 1](https://github.com/pfnet/optuna/issues/307#issuecomment-465465776) as the default pruning behavior because it's rather intuitive and has similar behavior to the lightgbm CV pruning.
- Define-by-run
    - We won’t support define-by-run interface with the SearchCV class. This is because the class requires a predefined search space and is incompatible with define-by-run. A downside is that nested, conditional search spaces are hard to describe with the SearchCV class.

**Comment by g-votte** [comment]
@Y-oHr-N 
If you are OK, we’d like to add [the SearchCV](https://github.com/Y-oHr-N/mllib/blob/master/mllib/model_selection.py) class to `optuna/integration/sklearn.py`. It’s great if we could have an additional logic for pruning like [the example above](https://github.com/pfnet/optuna/issues/307#issuecomment-465465776).

Are you interested in creating a PR?

**Comment by Y-oHr-N** [comment]
Yes, I will be pleased to create a PR!

However, most estimators, including `LGBMRegressor` and `XGBRegreessor`, do not have `partial_fit`. Do you mean we can not use pruning when they are learned?

**Comment by g-votte** [comment]
@Y-oHr-N 
Cool! Looking forward to your PR.

> However, most estimators, including `LGBMRegressor` and `XGBRegreessor`, do not have `partial_fit`. Do you mean we can not use pruning when they are learned?

Yes. In that case, the user would need to use Optuna in the standard way (i.e., write `objective` and invoke `study.optimize`) or additionally implement `partial_fit` extending the estimator, ..or just turn off pruning.

Just in our opinion, we prefer Option 1 because other options still may cause additional challenges of algorithm/interface design. In addition, we still can additionally implement other options in the future after we wrap up those challenges.

Feel free to let us know if you have any opinion or concern.

## Pros-and-cons of each pruning implementation

FYI: below is what we discussed in Optuna dev team.

- Option 1
  - Pros
    - Intuitive: we already have similar practices (e.g., lightgbm CV).
  - Cons
    - Dependent on `partial_fit`.
    - Possibly memory consuming: need to keep multiple estimator objects at the same time.
- Option 2
  - Pros
    - Independent of `partial_fit`.
  - Cons
    - This metrics typically does not results in decreasing/increasing curve. We are not sure if it is compatible with pruning algorithms like `MedianPruner` or `SuccessiveHalvingPruner`.
- Option 3
  - Pros
    - Independent of `partial_fit`.
  - Cons
    - We need to design scheduling method for data increasing.
    - Time consuming.
