### ISSUE TITLE
Resampling failed points

### ISSUE THREAD

**Issue by sdrobert** [pfnet/optuna#332]
Hello,

Thanks again for an amazing repository.

While Optuna allows for failed and pruned trials, the sampler does not seem to adjust for [them](https://github.com/pfnet/optuna/blob/2a90072001ea103a1c8e2e279dc2d8420c7200d1/optuna/samplers/tpe/sampler.py#L72). As a result, the sampler tends to resample the failed point a whole lot. For reference, of 11k points in my database, 27 did not fail.

I rely on the failure mechanism to handle model configurations that are too large for memory. In the case that the sampler cannot or will not be updated to account for failed or pruned trials, what mechanism do you suggest using with optuna to handle constraints?

Thanks very much,
Sean

**Comment by Minyus** [comment]
Hi Sean @sdrobert,

As an Optuna user, I agree that an option to avoid sampling the same parameter set (replacement = False) in the samplers will be useful.

In my case, I wanted to run grid search instead of optimization for benchmarking, but noticed that the duplicate parameter sets were run. 

As the workaround, I defined a pruner class that will prune (terminate the trial early) if the parameter set is found in the history in the Optuna's database. You can see my implementation as "RepeatPruner" class at: 
https://github.com/Minyus/optkeras/blob/master/optkeras/optkeras.py

You can use my workaround only if you do not need Optuna's pruner feature.

-Yusuke

**Comment by sdrobert** [comment]
Hi Yusuke @Minyus,

Thanks very much for your attention!

I might end up modifying your code to perform grid search with Optuna. Thanks!

My understanding of optuna's TPE sampler is that it ignores all pruned and failed points, though. So as soon as the trial is pruned, the sampler will just resample the point. :/

Best,
Sean

**Comment by g-votte** [comment]
Thanks @sdrobert for your reporting the issue, and thanks @Minyus for a workaround.

As @sdrobert pointed out, TPE sometimes converges to a certain parameter range so that most most suggested samples are pruned. Optuna dev team is discussing possible fixes for this problem, e.g., taking pruned samples to into the TPE algorithm.

**Comment by sile** [comment]
@sdrobert  `TPESampler` became to take into account pruned trials by #439 (this modification will be included in the next release of Optuna).
