### ISSUE TITLE
suggest_loguniform does not suggest params in the log domain.

### ISSUE THREAD

**Issue by tetsuyasu** [pfnet/optuna#343]
The sample code returns: 
[63.98388180987912, 0.05165898920982342, 0.7480453346996859, 1.8075943985379481, 1.3106044420872518, 0.011292787855683883, 0.004429228295529445]  (The values may be different.)

Isn't it correct to return the following value?
[1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 1e0, 1e1] (The order may be different.)

```
## sample code
import optuna
import random

class Objective(object):
    def __init__(self):
        self.history = []

    def __call__(self, trial):
        logval = trial.suggest_loguniform('logval', 1e-5, 1e2)
        self.history.append(logval)
        return random.random()

    def show_history(self):
        print(self.history)


study = optuna.create_study(pruner=optuna.pruners.MedianPruner)
objective = Objective()
study.optimize(objective, n_trials=7, timeout=None)
objective.show_history()
```

**Comment by toshihikoyanase** [comment]
Hi @tetsuyasu,

Thank you for your question.
The output values you showed meet our expectations. I will briefly explain the behaviors of `Trial.suggest_loguniform`. (Hereafter, I assume that we use `RandomSampler` instead of the default sampler for simplicity.)

At first, `Trial.suggest_uniform` samples values from a uniform distribution in linear space. We expect that the output values are scattered uniformly, and we will feel weird if the values are only on the lattice points.

![suggest_uniform](https://user-images.githubusercontent.com/3255979/54415844-e95a5080-4740-11e9-8a2a-4ef1c9e91b48.png)
A (linear) plot of `Trial.suggest_uniform('x', 1e-5, 1)`.

Then, `Trial.suggest_loguniform` is a counterpart of `Trial.suggest_uniform` in log-space, and it should be scattered uniformly in a log-log plot.

![loguniform](https://user-images.githubusercontent.com/3255979/54415831-e0697f00-4740-11e9-8bd6-a5d5678b45a5.png)
A (linear) plot of `Trial.suggest_loguniform('x', 1e-5, 1)`.

![loguniform_log_scale](https://user-images.githubusercontent.com/3255979/54415825-d8a9da80-4740-11e9-810b-2e1b7007ddf7.png)
A log-log plot of `Trial.suggest_loguniform('x', 1e-5, 1)`.

After all, we think the output values in your example are expected.

If you want to sample values only from [1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 1e0, 1e1]. Please use `Trial.suggest_int` instead of `Trial.suggest_loguniform` as follows:

```python
import optuna

def objective(trial):
        return 10**trial.suggest_int('logval', -5, 1)

study = optuna.create_study()
study.optimize(objective, n_trials=7, timeout=None)
print(study.trials_dataframe())
```

This small hack will ensure that all values are on the lattice points as follows:

![suggest_int_logscale2](https://user-images.githubusercontent.com/3255979/54415809-caf45500-4740-11e9-9e7c-286a451d5c1a.png)
A log-log plot of `10 ** Trial.suggest_int('x', -5, 0)`.

If you have further questions, please let us know.

**Comment by tetsuyasu** [comment]
Thank you for the clear answer.
I finally understood that "log domain" means "randomness that varies evenly in the log-space."
And thanks again for telling me the useful hack.

**Comment by eflopez1** [comment]
Thank you for the explanation. Could this possibly be included in the documentation? These images offer a great explanation.
