### ISSUE TITLE
Request for issue template

### ISSUE THREAD

**Issue by crcrpar** [pfnet/optuna#370]
Could you provide some issue templates such as feature request and bug report?

Also, it'd be really helpful if there is a piece of information about how to get help when I find difficulty in using optuna?
For example, chainer officially says I can get help in Slack, Google groups, and stackoverflow.

**Comment by toshihikoyanase** [comment]
Thank you for your request.
We are creating the issue template that includes information to get support. The current version is as follows:

```
If your issue is a **request for support in using Optuna**,
please post it on [Stack Overflow](https://stackoverflow.com/questions/tagged/optuna).
Support is also available on `#general` channel of [chainer slack](https://bit.ly/join-chainer-slack)
and [chainer-jp slack](https://bit.ly/join-chainer-jp-slack).

On registering an issue, write precise explanations on how you want Optuna to be.

Bug reports must include necessary and sufficient conditions to reproduce the bugs.
More specifically, it is helpful for us if you include the following information:

- Conditions
  - Optuna version
  - Python version
  - OS
  - Machine Learning library to be optimized
- Code to reproduce
- Error messages, stack traces, or logs

Feature requests are supposed to include what you want to do
(and why you want to do, if needed) with Optuna.
You can contain your thoughts on how to realize it into the feature requests, 
though what part is most important for discussions.

Thank you for your cooperation!
```

Hopefully, it will be released in a week or so.
If you have any feedback, please let us know.

**Comment by crcrpar** [comment]
Thank you for your response.
I drop some *NOT* critical comments.

---
> You can contain your thoughts on how to realize it into the feature requests, 
> though what part is most important for discussions.

The 2nd line seems interrogative and this makes the sentence a bit complex to me.

---

> - Conditions
>   - Optuna version
>   - Python version
>   - OS
>   - Machine Learning library to be optimized
> - Code to reproduce
> - Error messages, stack traces, or logs

I prefer the below template to the above.

**Conditions**
  - Optuna version: 
  - Python version: 
  - OS:
  - Machine Learning library to be optimized: 

**Code to reproduce**
```
# python code
```
**Error messages, stack traces, or logs**
```
# stack traces
```

**Comment by toshihikoyanase** [comment]
Thank you for your suggestion. I agree with you.
The current version is as follows:

---
If your issue is a **request for support in using Optuna**,
please post it on [Stack Overflow](https://stackoverflow.com/questions/tagged/optuna).
Support is also available on `#general` channel of [chainer slack](https://bit.ly/join-chainer-slack)
and [chainer-jp slack](https://bit.ly/join-chainer-jp-slack).

On registering an issue, write precise explanations on how you want Optuna to be.

Bug reports must include necessary and sufficient conditions to reproduce the bugs.
More specifically, it is helpful for us if you include the following information:

**Conditions**
- Optuna version:
- Python version:
- OS:
- Machine Learning library to be optimized:

**Code to reproduce**

```
# python code
```

**Error messages, stack traces, or logs**

```
# stack traces
```

Feature requests are supposed to include what you want to do
(and why you want to do, if needed) with Optuna.
You can optionally contain your thoughts on how to realize it into the feature requests.

Thank you for your cooperation!

---
Please give us a little more time for further review of the template.

**Comment by crcrpar** [comment]
This is nice to me. Thanks.

**Comment by toshihikoyanase** [comment]
@crcrpar 
We released the issue template.
Thank you again for your cooperation.
