### ISSUE TITLE
Dynamic Value space !

### ISSUE THREAD

**Issue by Enderdead** [pfnet/optuna#372]
Why don't support dynamic value space if parameters have the same type ?
It can be usefull  if I need a distribution depending on other dynamic parameter.

**Comment by sile** [comment]
Except categorical parameters, we already support dynamic value space. An example is found in [examples/lightgbm_simpl.py](https://github.com/pfnet/optuna/blob/master/examples/lightgbm_simple.py#L50).

**Comment by Enderdead** [comment]
I'm sorry but in your example you just have different generated arguments. 
Example :
```
if param['optimizer'] == 'SGD':
        param['learning_rate'] = trial.suggest_loguniform('learning_rate', 1e-8, 1.0)

if param['optimizer'] == 'Adam':
        param['learning_rate'] = trial.suggest_uniform('learning_rate', 0.0, 1.0)

 ```
It's impossible to do that and I don't understand why ?

**Comment by sile** [comment]
Sorry for the lack of explanation.
[examples/lightgbm_simple.py](https://github.com/pfnet/optuna/blob/master/examples/lightgbm_simple.py#L50) contains the following code and the value of  `high` argument of `trial.suggest_uniform('other_rate', ...)` changes dynamically during a study:


```python
if param['boosting_type'] == 'goss':
   param['top_rate'] = trial.suggest_uniform('top_rate', 0.0, 1.0)
   param['other_rate'] = trial.suggest_uniform('other_rate', 0.0, 1.0 - param['top_rate'])
```

As well, I believe the example code you wrote in the above comment can work.
(If you have errors when executing the code, it would be appreciated if you could let me know the detailed error log)

**Comment by Enderdead** [comment]
Sorry for my bad example. This is an example which don't works.

```
i = 0
def test(trial):
    global i
    i+=1
    if(i%2==0):
        trial.suggest_categorical("x", (2,3,4))
    else:
        trial.suggest_categorical("x", (1,2,3))
    return 0


study = optuna.create_study(study_name="test")
study.optimize(test,n_trials=2)
```

The Exception is  : 
```
  File "/usr/local/lib/python3.6/dist-packages/optuna/trial.py", line 296, in suggest_categorical
    return self._suggest(name, distributions.CategoricalDistribution(choices=choices))
  File "/usr/local/lib/python3.6/dist-packages/optuna/trial.py", line 408, in _suggest
    param_value_in_internal_repr, distribution)
  File "/usr/local/lib/python3.6/dist-packages/optuna/storages/in_memory.py", line 175, in set_trial_param
    distribution)
  File "/usr/local/lib/python3.6/dist-packages/optuna/distributions.py", line 214, in check_distribution_compatibility
    ' does not support dynamic value space.')
ValueError: CategoricalDistribution does not support dynamic value space.
```

**Comment by Rishav1** [comment]
@sile I think what he is talking about is that suggest_uniform distribution can be changed dynamically like the example you mentioned, but suggest_categorical cannot be changed dynamically because of [this check](https://github.com/pfnet/optuna/blob/2a90072001ea103a1c8e2e279dc2d8420c7200d1/optuna/distributions.py#L208-L211).

**Comment by sile** [comment]
@Enderdead @Rishav1 Yes. As I said briefly at the first comment, the current Optuna does not allow for changing `choices` of `suggest_categorical` dynamically.
It is because categorical has its own difficulties in interface design. For example, since `choices` are handled by its indices internally, the mapping between choice names and indices must be consistent across multiple trials. If `choices` could be changed, we would have to remap it appropriately.

Although a concrete schedule has not been decided, we would like to support to change `choices` dynamically in the future.

**Comment by jbgh2** [comment]
Maybe of help to future users: You may see this error if you change a `suggest_categorical` and Optuna loads a previously saved study.

**Comment by Enderdead** [comment]
I can close the issue?

**Comment by sile** [comment]
@Enderdead 

OK.
We have enqueued this issue to the TODO list that we maintain internally.

**Comment by gunnxx** [comment]
Hi @crownwang301 , you have error because of the following lines
```
optimizer_name = trial.suggest_categorical('optimizer', ['RMSprop','SGD'])
...
optimizer_name = trial.suggest_categorical('optimizer', ['Adam', 'Adadelta', 'Adagrad'])
```
Optuna already registered for hyperparameters named `'optimizer'`, there will be two choices only ie. `['RMSprop', 'SGD']`. However, in the next line, you create another hyperparameters named `'optimizer'` with different choices. This is called dynamic value space and apparently Optuna has no dynamic value space feature for `suggest_categorical()` as discussed above. I can't read you code fully, but seems like you make a mistake by reinitializing `optimizer` variables.

And please, next time, make sure to put your code between **three backticks (```)** so it is nicely formatted :)

**Comment by crownwang301** [comment]
thak you so much!!!!!

**Comment by beyarkay** [comment]
Is there any movement on adding dynamic categorical suggestions? It would be really helpful for my use case.

**Comment by jiange91** [comment]
I am just thinking out loud here. Please bear with me if this is a stupid idea.

Can I just create a new study with the new categorical parameter and migrate all previous trials here, would that be a valid workaround?  If this is legit, I think it solves the need for those whose dynamic categorical parameters evolve slowly.
The approach was originally proposed to solve parameter deletion/addition #2141.
