### ISSUE TITLE
More hyper-parameters optimization algorithms

### ISSUE THREAD

**Issue by emanueleparisi** [pfnet/optuna#552]
**CONDITIONS**
- Optuna version: 0.16.0

**FEATURE REQUEST**
Currently, the *Optuna* library supports two kind of samplers:
- random
- TPE

Do you plan to add support for other algorithms (e.g. grid search, simulated annealing, etc...) in next releases ?

Thank you in advance,
Emanuele

**Comment by toshihikoyanase** [comment]
In addition to `Random Search` and `TPE`, Optuna has supported [`Gaussian Process`](https://optuna.readthedocs.io/en/stable/reference/integration.html#optuna.integration.SkoptSampler) and [`CMA-ES`](https://optuna.readthedocs.io/en/stable/reference/integration.html#optuna.integration.CmaEsSampler) since v0.13.0 and v0.14.0, respectively.

We would like to implement more sampling algorithms in future releases.

And also, users are able to define their own samplers. For example, [this tutorial](https://optuna.readthedocs.io/en/stable/tutorial/sampler.html) explains how to implement Simulated Annealing.

Thanks.

**Comment by emanueleparisi** [comment]
Wow, interesting, I missed that !

Thank you for the clarification,
Emanuele
